### ISSUE TITLE
Relation to other pass packages?

### ISSUE THREAD

**Issue by DamienCassou** [pjones/passmm#2]
I have the impression what you want to do as been covered by https://petton.fr/git/nico/pass already. Also, please note the existence of these related packages:

- [password-store](https://git.zx2c4.com/password-store/tree/contrib/emacs/password-store.el): password store (pass) support;
- [auth-password-store](https://github.com/DamienCassou/auth-password-store): integrate Emacs' auth-source with password-store;
- [helm-pass](https://github.com/jabranham/helm-pass): helm interface for pass.

**Comment by pjones** [comment]
Thanks for the links.

I think that each package (including passmm) handles things a bit differently.  I don't see a problem with me making another solution available.
